name: build-chartdb

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            working-directory: ./
        permissions: write-all

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: 'npm'
                  cache-dependency-path: './package-lock.json'
            - name: Install
              run: npm ci
            - name: Build chartdb
              run: npm run build
